baseurl = "https://avarco.github.io"
languageCode = "en-us"
title = "$AVC | ICO"
theme = "bulma"
copyright = ""
publishdir = "avarco.github.io"

[Author]
	name = "Author Name"

[Permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "Site description"
	twitter = "https://twitter.com/xyz"
	github = "https://github.com/xyz"
	disqus = ""
